interface IProcessEnv {
  APP_ENV_HANDLER_SEPARATOR: string;
  APP_ENV_VAR_WORD_SEPARATOR: string;
  NODE_ENV: string;
  APP_DEBUG: string;
  NODE_DEBUG: string;
  APP_I18N_LOCALE_DEFAULT: string;
  APP_I18N_LOCALE_DUMMY: string;
  APP_I18N_SUPPORTED_LOCALES: string;
  APP_I18N_SWITCHER_BEHAVIOUR: string;
  APP_I18N_SWITCHER_CHECK_PATH_LOCALE: string;
  APP_ENV_MISSABLE: string;
  APP_ENV_TEST: string;
  APP_ENV_TEST_SECOND: string;
  APP_ENV_TEST_THIRD: string;
  APP_E2E_PROTRACTOR_DIRECT_CONNECT?: string;
  APP_E2E_PROTRACTOR_BASE_URL?: string;
  APP_E2E_PROTRACTOR_SELENIUM_ADDRESS?: string;
}
